### PR TITLE
Try and fail to implement a directive @constraint

### PR DESCRIPTION
**Pull request by jmfayard**
### :pencil: Description

Helo, I tried and failed to implement a GraphQL directive as explained here 
-> https://opensource.expediagroup.com/graphql-kotlin/docs/schema-generator/customizing-schemas/directives#custom-directives

Dariusz Kuc asked  me on Slack to provide a sample that shows the issue and here it is.

Reproducing steps:

- run the `:ktor-server:run`  Gradle task
- fetch the GraphQL schema

### Expected:

```
"This GraphQL directive allows to add constraints to the GraphQL Schema - https://www.apollographql.com/blog/backend/validation/graphql-validation-using-directives/"
directive @constraint(format: String!, maxLength: Int!, minLength: Int!, pattern: String!) on VARIABLE_DEFINITION | FIELD_DEFINITION | INPUT_OBJECT

input DirectiveInput {
    deviceId: String! @constraint(minLength: 8, maxLength: 16)
    email: String! @constraint(format: "email")
}


type DirectivePayload {
    deviceId: String! @constraint(minLength: 8, maxLength: 16)
    email: String! @constraint(format: "email")
}
```

### Got:

```
"This GraphQL directive allows to add constraints to the GraphQL Schema - https://www.apollographql.com/blog/backend/validation/graphql-validation-using-directives/"
directive @constraint(format: String!, maxLength: Int!, minLength: Int!, pattern: String!) on VARIABLE_DEFINITION | FIELD_DEFINITION | INPUT_OBJECT

input DirectiveInput {
    deviceId: String!
    email: String!
}


type DirectivePayload {
    deviceId: String!
    email: String!
}
```

### CODE REVIEW

**Comment by dariuszkuc** [comment]
How are you printing the schema? When I updated `ktorGraphQLSchema.kt` to print it before returning new schema object (and also added `ARGUMENT_DEFINITION` to the directive target locations)

```kotlin
fun getGraphQLObject(): GraphQL {
    println(graphQLSchema.print()) // print out SDL
    return GraphQL.newGraphQL(graphQLSchema).build()
}
``` 

I got following schema printed out (omitted non interesting parts)

```graphql
"This GraphQL directive allows to add constraints to the GraphQL Schema - https://www.apollographql.com/blog/backend/validation/graphql-validation-using-directives/"
directive @constraint(format: String!, maxLength: Int!, minLength: Int!, pattern: String!) on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_OBJECT | INPUT_FIELD_DEFINITION

type DirectivePayload {
  deviceId: String! @constraint(format : "", maxLength : 16, minLength : 8, pattern : "")
  email: String! @constraint(format : "email", maxLength : 2147483647, minLength : 1, pattern : "")
}

type Mutation {
  directive(input: DirectiveInput!): DirectivePayload!
  login(aliasUUID: String, email: String! @constraint(format : "email", maxLength : 2147483647, minLength : 1, pattern : ""), password: String!): AuthPayload!
}

input DirectiveInput {
  deviceId: String! @constraint(format : "", maxLength : 16, minLength : 8, pattern : "")
  email: String! @constraint(format : "email", maxLength : 2147483647, minLength : 1, pattern : "")
}
```

**Comment by jmfayard** [comment]
I was using IntelliJ's plugin for GraphQL to generate the schema https://plugins.jetbrains.com/plugin/8097-graphql

This was the issue, this plugin does not print the directive

I added a unit test that re-generates the schema using `graphQLSchema.print()` and it all works

Thanks a lot for your help @dariuszkuc

**Comment by dariuszkuc** [comment]
Pretty sure that plugin (same as most of the tooling) relies on introspection to get the schema (which does not include directive information, see https://github.com/graphql/graphql-spec/issues/300). Generally you will only be able to get the schema with the directives if you explicitly print it out (e.g. in `spring-server` we expose `/sdl` endpoint).

**Comment by jmfayard** [comment]
Follow up: https://github.com/ExpediaGroup/graphql-kotlin/pull/1351

**Pull request closed without merging**
