### PR TITLE
feat: add GraphQLContext extension functions

### PR DESCRIPTION
**Pull request by samuelAndalon**
### :pencil: Description
In the `GraphQLContext` map we often use `KClass` as a key

```kotlin
environment.graphQlContext.getOrDefault(CoroutineScope::class, CoroutineScope(EmptyCoroutineContext))
```

adding some inline reified extension functions to reduce the verbosity to allow

```kotlin
// explicitly provide type
val scope = environment.graphQlContext.get<CoroutineScope>() // return nullable 
// type can also be inferred
val scope: CoroutineScope = environment.graphQlContext.get()

// provide default value, type inferred from default value
environment.graphQlContext.getOrDefault(CoroutineScope(EmptyCoroutineContext))

// provide lambda to compute default value, type inferred from default value
environment.graphQlContext.getOrElse { CoroutineScope(EmptyCoroutineContext) } 
```

### :link: Related Issues
Resolves https://github.com/ExpediaGroup/graphql-kotlin/issues/1365

### CODE REVIEW

**Review by dariuszkuc — APPROVED** [review]

**Comment by zsiegel** [comment]
I think this has broken the functionality described [here](https://opensource.expediagroup.com/graphql-kotlin/docs/server/graphql-context-factory#coroutine-context).

This reified version when used like so 

```kt
environment.graphQlContext.getOrDefault(CoroutineScope(EmptyCoroutineContext)).future {

}
```

Will look in the context for a `class kotlin.coroutines.EmptyCoroutineContext` and will not look for `class kotlin.coroutines.CoroutineContext` which is what is indicated in the docs referenced above.

Happy to open a bug or provide a PR for this unless I am somehow mistaken? Eagerly testing this functionality out for usage with `MDCContext`

**Comment by samuelAndalon** [comment]
These extension functions are meant to be applied when the value of on the `graphqlContext` is an instance of the `KClass` provided as a key

for this example

```kotlin
environment.graphQlContext.getOrDefault(CoroutineScope(EmptyCoroutineContext)).future {
}
```
Will look in the context  for the KClass key `CoroutineScope::class` and will try to cast the value (if present) as instance of `CoroutineScope`

**Comment by zsiegel** [comment]
Got it!

So the expectation is that a `scope` is passed. Should this be reflected and updated in the docs here - https://opensource.expediagroup.com/graphql-kotlin/docs/server/graphql-context-factory/#coroutine-context? 

These to me look out of sync or maybe I am missing the place where you can simply inject a context? Trying to figure out how the upcoming 6.x.x docs are mapped in any way to the code in master but in in the 5.x.x latest release.

Thanks!

**Comment by zsiegel** [comment]
@dariuszkuc ahhh thats the missing piece for me thank you! Will see if I can work this into my Spring based project.

**Comment by dariuszkuc** [comment]
@zsiegel once we get the batching PRs in (hopefully soon) we should start releasing first previews of 6.0

**Comment by zsiegel** [comment]
thats great. I was easily able to shim the small changes into my `GraphQLServer` in my spring project. Will give the `6.x.x` releases a test drive as soon as they are available.

**Pull request merged**
