### PR TITLE
versioned docs: replace references to `master` branch with `3.x.x`

### PR DESCRIPTION
**Pull request by koenpunt**

### CODE REVIEW

**Comment by dariuszkuc** [comment]
Since those are docs for `3.x.x` they probably should point to appropriate branch -> https://github.com/ExpediaGroup/graphql-kotlin/tree/3.x.x/examples/spring

I'd imagine a number of old code links will be invalid as they are pointing to `master` vs `3.x.x` branch.

**Comment by koenpunt** [comment]
I've updated all references to master in the versioned_docs path to `3.x.x`

**Review by dariuszkuc — APPROVED** [review]
Awesome! Thanks for fixing this

**Comment by smyrick** [comment]
Amazing! 😍  Thank you @koenpunt for the documentation updates!

**Pull request merged**
