### PR TITLE
[spring-server] default data fetcher should use Jackson object mapper from spring context

### PR DESCRIPTION
**Pull request by dariuszkuc**
### :pencil: Description
Currently it is not possible to provide custom Jackson object mapper (e.g. one that includes java date time module) to be used by default function data fetcher. In order to use custom object mapper users have to create their own instance of data fetcher factory provider. This change updates the data fetcher factory provider to accept an instance of object mapper that will be used by the function data fetcher.

### :link: Related Issues
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/524

### CODE REVIEW

**Comment by smyrick** [comment]
LGTM

**Comment by smyrick** [comment]
Is this ready for review? Was there some other feature you were looking to add?

**Comment by dariuszkuc** [comment]
> Is this ready for review? Was there some other feature you were looking to add?

Looking into adding some unit test for this.

**Comment by smyrick** [comment]
@dariuszkuc This look good to me. We have the single test. Is this good to merge?

**Comment by dariuszkuc** [comment]
@smyrick this should be good to merge - was looking into whether we need to have that jackson object mapper in the first place and unfortunately it is required in order to process any complex input objects. 

On the side note - currently we do an extra conversion from primitive scalar value to the same scalar type (as noted [here](https://github.com/ExpediaGroup/graphql-kotlin/issues/518#issuecomment-566996194)). Unsure how big of a perf impact that is but we might want to optimize it as well.

**Comment by smyrick** [comment]
Major version changes now that we changed from class to interface

**Pull request merged**
