### PR TITLE
Don't swallow root server exceptions

### PR DESCRIPTION
**Pull request by dakriy**
Let root level bootstrap exceptions go to the ktor exception handler rather than being swallowed.

### :pencil: Description
Exceptions that happen when building the context are swallowed obscuring what actually went wrong and making it hard to fix.

### :link: Related Issues
#1920

### CODE REVIEW

**Comment by curtiscook** [comment]
Hi @samuelAndalon can we get this merged?

**Comment by dariuszkuc** [comment]
Server should not respond with exception stacktraces. Exceptions should be logged instead.

**Comment by curtiscook** [comment]
> Server should not respond with exception stacktraces. Exceptions should be logged instead.

I don't understand your point here and it doesn't read constructively. 

Currently, any exception throws a 400 error with no message and I have no control over the error code or messaging. 

As you know... Some errors are 400, some are 401, 403, 500, or 503. Technically, since you're catching a base exception, it should be a 500 error. If you look through all the code it looks like maybe people should be catching errors and rethrowing a GraphQLError that can provide a message, but I'm still not seeing where I can set the status code. 

Honestly, the "correct" way to handle this should be to let KTor (or Spring) handle the exception and map any unhandled exceptions to a 500 status code, which could easily be part of the example. 

Or at the very least, I think there could be some documentation on suggested error handling.

**Comment by dariuszkuc** [comment]
Superseded by https://github.com/ExpediaGroup/graphql-kotlin/pull/1936

**Pull request closed without merging**
