### PR TITLE
[generator] Move type generator to separate class

### PR DESCRIPTION
**Pull request by smyrick**
### :pencil: Description
Expose a new public class, `TypeGenerator`, that allows anyone to convert any `KType` to a `GraphQLType`. This could be used outside the schema generator if needed

### :link: Related Issues
https://github.com/ExpediaGroup/graphql-kotlin/issues/863

### CODE REVIEW

**Comment by dariuszkuc** [comment]
Whats the use case behind this?

**Comment by smyrick** [comment]
We have had a few people ask about generating code outside of a full schema or getting access to just the generator.

We could also use this internally for our shared types in Expedia since we just use a mock query object.

This could be seen as leaking internals which is why I wanted more opinions but the only new method is `generateType`. The config options are still the external ones!

**Comment by dariuszkuc** [comment]
IMHO it is leaking internals of the library. One potential problem scenario could arise when custom hooks would use their own instance of type generator to build some custom types (which is good) but since it would use separate type cache (from the schema generator) there is a potential for some conflicts.

I think we should revisit our hooks to make it more useable.

**Comment by smyrick** [comment]
We are going to close this as it does raise some complications

* What happens when you call it twice with the same type, you will get a type reference back that you can't really do anything with.
* We now have more coverage or areas that require a major version if we ever want to introduce a breaking change
* This can be solve by creating a simple query object, even if not used, and generating a full schema, either by using the types or using the additional types


If we have more requests for something similar to this in the future we can reopen the PR

**Pull request closed without merging**
