### PR TITLE
Support built-in `ID` type serialization in `GraphQLServerRequest`

### PR DESCRIPTION
**Pull request by T45K**
#### Problem
after graphql-kotlin 7.1.0, the following `GraphQLRequest` our team uses started to fail.

```kotlin
GraphQLRequest(
    "query(${'$'}id: ID!) { ... }",
    variables = mapOf("id" to ID("1"))
)
```

this is because `kotlinx.serialization` is recently introduced instead of Jackson, but `ID` serialization is missing, so it is converted to `JsonNull`.

since `ID` is built-in scalar type, i think `ID` serialization should be supported.

#### Solution
add serialization logic to `AnyNullableKSerializer` 

### :link: Related Issues
N/A

### CODE REVIEW

**Comment by samuelAndalon** [comment]
Thank you for the pr, could you adjust the jacoco thresholds ?
> Rule violated for bundle graphql-kotlin-server: branches covered ratio is 0.71, but expected minimum is 0.72

**Comment by T45K** [comment]
@samuelAndalon 
thank you for review!

sure, i added a test that covers my change to `GraphQLServerRequestTest`

please check again :bow:

**Comment by T45K** [comment]
hmm, `build-example` still failed but i cannot find out the cause

`Error:  Plugin com.expediagroup:graphql-kotlin-maven-plugin:7.0.0-SNAPSHOT or one of its dependencies could not be resolved: The following artifacts could not be resolved: com.expediagroup:graphql-kotlin-maven-plugin:jar:7.0.0-SNAPSHOT (absent): Could not find artifact com.expediagroup:graphql-kotlin-maven-plugin:jar:7.0.0-SNAPSHOT -> [Help 1]`

could you tell me what is wrong?

**Comment by dariuszkuc** [comment]
👋 re: example build failure -> that was my miss in the version bump. This should fix it -> https://github.com/ExpediaGroup/graphql-kotlin/pull/1953

**Comment by T45K** [comment]
@dariuszkuc 
i see.
after PR you created is merged into main branch, i'll merge main branch again, and then CI failure will be fixed

**Comment by T45K** [comment]
updated
could you check again 🙏

**Review by samuelAndalon — APPROVED** [review]

**Pull request merged**
