### PR TITLE
fix subscriptions by not removing the ak subscription when one of the…

### PR DESCRIPTION
**Pull request by gklijs**
### :pencil: Description
Prevents stopping ka when ending a subscription

### :link: Related Issues
#499 I hoped, but is not helped by it.

### CODE REVIEW

**Comment by smyrick** [comment]
@gklijs I tried checking out your performance benchmarks but the step up was taking a little bit longer than expected since I have not used clojure before

Is it possible that you can update the `SubscriptionWebSocketHandler.handle` method to this.

```kotlin
override fun handle(session: WebSocketSession): Mono<Void> {
        val response = session.receive()
            .map { it.payloadAsText }
            .flatMap { subscriptionHandler.handle(it, session) }
            .map { objectMapper.writeValueAsString(it) }
            .map { session.textMessage(it) }
            .doFinally { session.close() }

        return session.send(response)
    }
```

While the handler should close the session when receiving a `GQL_CONNECTION_TERMINATE` message, I just want to make sure that the session is in fact closing and not eating up the memory.

**Comment by smyrick** [comment]
On a side note, I tried using sending the data over as bytes instead of converting to a string to see if that improved performance, but I my quick change did not seem to work so I will need to look into that more

```kotlin
val response = session.receive()
            .map { it.payloadAsText }
            .flatMap { subscriptionHandler.handle(it, session) }
            .map { objectMapper.writeValueAsBytes(it) }
            .map { session.binaryMessage { dataBufferFactory -> dataBufferFactory.wrap(it) } }
            .doFinally { session.close() }
```

**Comment by gklijs** [comment]
I'll give it a try tomorrow. You indeed need leiningen (build tool for Clojure) and sassc installed. Now that I better know the problem I might try create a test in the project itself trough.
Binary data is handled differently as string values in a websocket so that might be reason it fails. I don't that's a good idea because clients might break because of it.

**Comment by gklijs** [comment]
The mentioned fix https://github.com/ExpediaGroup/graphql-kotlin/pull/510#issuecomment-563370716 didn't help. It's still stops after around 120 subscriptions being started and stopped.

**Comment by smyrick** [comment]
@gklijs Can you try adding in these changes: https://github.com/ExpediaGroup/graphql-kotlin/pull/512

We don't need to save the session connections, because to cancel them later on we reference by session id, so we can just directly cancel the session on `GQL_CONNECTION_TERMINATE`. The open client streams can be cancelled if the client then sends `GQL_STOP`

**Comment by gklijs** [comment]
Finally kind of done updating the results (not all variants ran 10 times, would improve accuracy a bit, but not much) https://graphql.gklijs.tech/results/graphql-servers/transactions-per-second

**Pull request merged**
