### PR TITLE
Make GraphQLGenerateClientTask and GraphQLGenerateTestClientTask cacheable

### PR DESCRIPTION
**Pull request by ajaybirratoul**
### :pencil: Description
- We can leverage caching in Gradle for `GraphQLGenerateClientTask` and `GraphQLGenerateTestClientTask` by annotating them with `@CacheableTask` 
- Also annotate `schemaFile`, `queryFileDirectory`, `queryFiles` with `@PathSensitive(PathSensitivity.RELATIVE)` for the purposes of normalization so that outputs can be reused for caching
- Gradle docs: https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/CacheableTask.html

### CODE REVIEW

**Comment by dariuszkuc** [comment]
Can you also update the test client generation task to cacheable?

**Comment by ajaybirratoul** [comment]
> Can you also update the test client generation task to cacheable?

@dariuszkuc done!

**Review by dariuszkuc — APPROVED** [review]

**Comment by dariuszkuc** [comment]
@ajaybirratoul looks like some additional changes are needed?

**Comment by ajaybirratoul** [comment]
@dariuszkuc it seems like we need to declare a normalization strategy for some of the properties when enabling caching ([workflow output](https://github.com/ExpediaGroup/graphql-kotlin/actions/runs/9668851479/job/26767228224?pr=1986))

image

I've made the recommend change by annotating relevant properties with `@PathSensitive(PathSensitivity.RELATIVE)`.

**Pull request merged**
