### PR TITLE
Documentation: Fix typos and a broken link

### PR DESCRIPTION
**Pull request by Inego**

### CODE REVIEW

**Comment by Inego** [comment]
> can you remove the `.md` suffixes from the links?

Oh, the problem seems to be worse than I thought. These pages can be navigated both on expediagroup.github.io/graphql-kotlin/docs and here on GitHub. And GitHub doesn't support navigation to pages without the `.md` extension (since that's the exact file name), while the generated help site has the problem the other way.

I honestly don't even know what to do :(

**Comment by Inego** [comment]
For example, if you open this page on GitHub:

https://github.com/ExpediaGroup/graphql-kotlin/blob/master/docs/schema-generator/execution/contextual-data.md

and try to click the link from there:
image

... you get a 404.

Probably it's just not supposed to be used like that since these files are only source files for an external docs site.

**Comment by Inego** [comment]
Rolled back .md extensions and fixed a couple of typos in other places on the way.

**Comment by smyrick** [comment]
Merged as the library checks are not needed. Yea we don't need to be able to navigate from the source code of markdown docs, this is all about the generated links in the docs site.

Thanks for the contributions!

**Pull request merged**
